// Generated by gencpp from file cav_project/limo_state_matrix.msg
// DO NOT EDIT!


#ifndef CAV_PROJECT_MESSAGE_LIMO_STATE_MATRIX_H
#define CAV_PROJECT_MESSAGE_LIMO_STATE_MATRIX_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <cav_project/limo_state.h>

namespace cav_project
{
template <class ContainerAllocator>
struct limo_state_matrix_
{
  typedef limo_state_matrix_<ContainerAllocator> Type;

  limo_state_matrix_()
    : limos()  {
    }
  limo_state_matrix_(const ContainerAllocator& _alloc)
    : limos(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::cav_project::limo_state_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::cav_project::limo_state_<ContainerAllocator> >> _limos_type;
  _limos_type limos;





  typedef boost::shared_ptr< ::cav_project::limo_state_matrix_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cav_project::limo_state_matrix_<ContainerAllocator> const> ConstPtr;

}; // struct limo_state_matrix_

typedef ::cav_project::limo_state_matrix_<std::allocator<void> > limo_state_matrix;

typedef boost::shared_ptr< ::cav_project::limo_state_matrix > limo_state_matrixPtr;
typedef boost::shared_ptr< ::cav_project::limo_state_matrix const> limo_state_matrixConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cav_project::limo_state_matrix_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cav_project::limo_state_matrix_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cav_project::limo_state_matrix_<ContainerAllocator1> & lhs, const ::cav_project::limo_state_matrix_<ContainerAllocator2> & rhs)
{
  return lhs.limos == rhs.limos;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cav_project::limo_state_matrix_<ContainerAllocator1> & lhs, const ::cav_project::limo_state_matrix_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cav_project

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cav_project::limo_state_matrix_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cav_project::limo_state_matrix_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cav_project::limo_state_matrix_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cav_project::limo_state_matrix_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cav_project::limo_state_matrix_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cav_project::limo_state_matrix_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cav_project::limo_state_matrix_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8726c45313017f9857b70bc15ddc333f";
  }

  static const char* value(const ::cav_project::limo_state_matrix_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8726c45313017f98ULL;
  static const uint64_t static_value2 = 0x57b70bc15ddc333fULL;
};

template<class ContainerAllocator>
struct DataType< ::cav_project::limo_state_matrix_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cav_project/limo_state_matrix";
  }

  static const char* value(const ::cav_project::limo_state_matrix_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cav_project::limo_state_matrix_<ContainerAllocator> >
{
  static const char* value()
  {
    return "limo_state[] limos\n"
"\n"
"================================================================================\n"
"MSG: cav_project/limo_state\n"
"string limoID\n"
"float64 vel\n"
"float64 d0\n"
"float64 d1\n"
"float64 v1\n"
"float64 d2\n"
"float64 v2\n"
;
  }

  static const char* value(const ::cav_project::limo_state_matrix_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cav_project::limo_state_matrix_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.limos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct limo_state_matrix_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cav_project::limo_state_matrix_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cav_project::limo_state_matrix_<ContainerAllocator>& v)
  {
    s << indent << "limos[]" << std::endl;
    for (size_t i = 0; i < v.limos.size(); ++i)
    {
      s << indent << "  limos[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::cav_project::limo_state_<ContainerAllocator> >::stream(s, indent + "    ", v.limos[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAV_PROJECT_MESSAGE_LIMO_STATE_MATRIX_H
